import type { Product, ProductCategory } from '@/types/catalog'

export const mockCategories: ProductCategory[] = [
  {
    id: 'fuego',
    name: 'Fuego',
    description: 'Piezas intensas con acentos cálidos, presencia escénica y terminaciones densas.',
    note: 'Serie para editorial y vitrinas de alto contraste.',
    accent: '#8f4d2c',
    productCount: 3,
  },
  {
    id: 'ritual',
    name: 'Ritual',
    description: 'Máscaras de líneas sobrias, textura mate y espíritu ceremonial contemporáneo.',
    note: 'Pensadas para coleccionistas y piezas de firma.',
    accent: '#7d6a52',
    productCount: 2,
  },
  {
    id: 'agua',
    name: 'Agua',
    description: 'Volúmenes fluidos, curvas sutiles y paleta fría para una lectura más silenciosa.',
    note: 'Ideal para composición visual y dirección de arte.',
    accent: '#315368',
    productCount: 2,
  },
]

export const mockProducts: Product[] = [
  {
    id: 'kitsune-ember',
    name: 'Kitsune Ember',
    slug: 'kitsune-ember',
    category: 'Fuego',
    categoryId: 'fuego',
    description: 'Máscara de carácter afilado, base negra y veladuras cobre para puestas editoriales.',
    price: 64990,
    status: 'published',
    availability: 'available',
    accent: '#8f4d2c',
    material: 'Resina pigmentada y laca mate',
    edition: 'Edición abierta',
    featured: true,
  },
  {
    id: 'oni-nocturna',
    name: 'Oni Nocturna',
    slug: 'oni-nocturna',
    category: 'Ritual',
    categoryId: 'ritual',
    description: 'Volumen frontal robusto con terminación satinada y gesto dramático.',
    price: 78990,
    status: 'published',
    availability: 'limited',
    accent: '#5d2633',
    material: 'Fibra compuesta y pigmento mineral',
    edition: 'Serie limitada / 12 piezas',
    featured: true,
  },
  {
    id: 'koi-eclipse',
    name: 'Koi Eclipse',
    slug: 'koi-eclipse',
    category: 'Agua',
    categoryId: 'agua',
    description: 'Perfil fluido con lectura lateral elegante, pensado para vitrinas y colección.',
    price: 49990,
    status: 'published',
    availability: 'available',
    accent: '#315368',
    material: 'Resina pulida y tinte translúcido',
    edition: 'Edición abierta',
    featured: true,
  },
  {
    id: 'tengu-slate',
    name: 'Tengu Slate',
    slug: 'tengu-slate',
    category: 'Ritual',
    categoryId: 'ritual',
    description: 'Pieza de líneas tensas y gesto vertical para dirección de arte sobria.',
    price: 71990,
    status: 'published',
    availability: 'sold-out',
    accent: '#4b5157',
    material: 'Resina oscura con textura mineral',
    edition: 'Serie limitada / agotada',
    featured: false,
  },
  {
    id: 'akuma-umber',
    name: 'Akuma Umber',
    slug: 'akuma-umber',
    category: 'Fuego',
    categoryId: 'fuego',
    description: 'Máscara escultórica con relieve artesanal y base profunda en tonos tierra.',
    price: 82990,
    status: 'published',
    availability: 'limited',
    accent: '#6f3d27',
    material: 'Compuesto liviano y pigmento al óleo',
    edition: 'Serie limitada / 8 piezas',
    featured: false,
  },
  {
    id: 'nami-veil',
    name: 'Nami Veil',
    slug: 'nami-veil',
    category: 'Agua',
    categoryId: 'agua',
    description: 'Curva envolvente y lectura serena para sesiones, escaparates y coleccionismo.',
    price: 58990,
    status: 'published',
    availability: 'available',
    accent: '#2d6674',
    material: 'Resina semimate y capa translúcida',
    edition: 'Edición abierta',
    featured: false,
  },
  {
    id: 'oni-cinder-study',
    name: 'Oni Cinder Study',
    slug: 'oni-cinder-study',
    category: 'Fuego',
    categoryId: 'fuego',
    description: 'Estudio de taller reservado como base para futuras variaciones de colección.',
    price: 75990,
    status: 'draft',
    availability: 'limited',
    accent: '#7e4630',
    material: 'Prototipo de resina con prueba de pigmento',
    edition: 'No publicado',
    featured: false,
  },
]

export const publishedProducts = mockProducts.filter(
  (product) => product.status === 'published',
)

export const featuredProducts = publishedProducts.filter((product) => product.featured)
